import React from 'react'
import Head from 'next/head'


const HeadInfos = ({title, keyword, contents}) => {
  return (
    <Head>
      <title>{ title }</title>
      <meta keyword={ keyword }/>
      <meta contents={ contents }/>
    </Head>
  )
}

HeadInfos.defaultProps = {
  title: 'My blog',
  keyword: "generated by next.js",
  contents: "generated by next.js"
}


export default HeadInfos
